import type { NextPage } from "next";
import Head from "next/head";
import { RegisterForm } from "../components/RegisterForm";

const Register: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen">
      <Head>
        <title>meta-my-tickets</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RegisterForm />
    </div>
  );
};

export default Register;
